# Generated by Django 5.0.1 on 2024-02-01 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='emailid',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='ourservices',
            field=models.CharField(choices=[('Web development', 'Web development'), ('Digital marketing', 'Digital marketing'), ('Paid service', 'Paid service'), ('SEO', 'SEO')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phonenumber',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='Phone number must only contain numeric values.', regex='^[0-9]+$')]),
        ),
        migrations.AddField(
            model_name='contactform',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
