# Generated by Django 5.0.1 on 2024-02-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_remove_contactform_name_alter_contactform_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
