# Generated by Django 5.0.1 on 2024-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0004_emailconfiguration_alter_contactform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='recipient_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
