# Generated by Django 5.0.1 on 2024-02-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0005_emailconfiguration_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_host_password',
            field=models.CharField(default='pbsiqfeamugrajqk', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_host_user',
            field=models.CharField(default='rajanvigneesh56@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='recipient_email',
            field=models.EmailField(default='vigneshbsc048@gmail.com', max_length=255),
        ),
    ]
