# Generated by Django 5.0.1 on 2024-02-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0007_emailsettings_delete_emailconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSettings',
        ),
    ]
