# Generated by Django 5.0.1 on 2024-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0009_contactform_recipient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='emailid',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
