# Generated by Django 5.0.1 on 2024-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0010_recipientemail_remove_contactform_recipient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
