# Generated by Django 5.0.1 on 2024-03-22 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0012_portfolioitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
