# Generated by Django 5.0.1 on 2024-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0013_delete_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstsection', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
