# Generated by Django 5.0.1 on 2024-03-26 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0017_image_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
