# Generated by Django 5.0.1 on 2024-03-27 07:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0019_firstsection_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length='200')),
                ('subtitle', ckeditor.fields.RichTextField(max_length=200)),
                ('subtitleone', ckeditor.fields.RichTextField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
