# Generated by Django 5.0.1 on 2024-03-27 11:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0021_thirdsection_alter_secondsection_subtitleone'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdsection',
            name='text1',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thirdsection',
            name='text2',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thirdsection',
            name='text3',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
    ]
