# Generated by Django 5.0.1 on 2024-03-28 06:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0022_thirdsection_text1_thirdsection_text2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourthsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png1', models.ImageField(upload_to='images/')),
                ('png2', models.ImageField(upload_to='images/')),
                ('title', ckeditor.fields.RichTextField(default='', max_length='200')),
                ('subtitle', ckeditor.fields.RichTextField(max_length=200)),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=200)),
                ('lap_image', models.ImageField(upload_to='images/')),
                ('poster_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
