# Generated by Django 5.0.1 on 2024-03-28 08:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0023_fourthsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifthsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png1', models.ImageField(upload_to='images/')),
                ('png2', models.ImageField(upload_to='images/')),
                ('title', ckeditor.fields.RichTextField(default='', max_length='200')),
                ('subtitle', ckeditor.fields.RichTextField(max_length=200)),
                ('ourservice_heading', models.CharField(max_length=200)),
                ('ourservice_content', models.CharField(max_length=200)),
                ('ourservice_png', models.CharField(max_length=200)),
                ('ourservice_link', models.CharField(max_length=200)),
            ],
        ),
    ]
