# Generated by Django 5.0.1 on 2024-03-28 09:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0025_alter_fifthsection_ourservice_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthsection',
            name='png1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length='200', null=True),
        ),
    ]
