# Generated by Django 5.0.1 on 2024-03-28 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0026_alter_fifthsection_png1_alter_fifthsection_png2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifthsectioncontainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourservice_heading', ckeditor.fields.RichTextField(max_length=200)),
                ('ourservice_content', ckeditor.fields.RichTextField(max_length=200)),
                ('ourservice_png', models.ImageField(max_length=200, upload_to='')),
                ('ourservice_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_content',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_heading',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_link',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_png',
        ),
    ]
