# Generated by Django 5.0.1 on 2024-03-28 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0027_fifthsectioncontainer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fifthsectioncontainer',
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='ourservice_content',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='ourservice_heading',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='ourservice_link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='ourservice_png',
            field=models.ImageField(default='', max_length=200, upload_to=''),
        ),
    ]
