# Generated by Django 5.0.1 on 2024-03-30 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0028_delete_fifthsectioncontainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sixthsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('png1', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sixthsectiontest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=200)),
                ('png1', models.ImageField(upload_to='images/')),
                ('png2', models.ImageField(upload_to='images/')),
                ('png3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
