# Generated by Django 5.0.1 on 2024-03-30 06:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0029_sixthsection_sixthsectiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixthsection',
            name='test_png1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='test_png2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='test_png3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='test_subtitle',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='test_title',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sixthsection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sixthsection',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
