# Generated by Django 5.0.1 on 2024-03-30 11:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0030_sixthsection_test_png1_sixthsection_test_png2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eighthsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Seventhsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=200)),
                ('png', models.ImageField(upload_to='images/')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=200)),
            ],
        ),
    ]
