# Generated by Django 5.0.1 on 2024-04-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0031_eighthsection_seventhsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdsection',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='thirdsection',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='thirdsection',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='thirdsection',
            name='text3',
        ),
    ]
