# Generated by Django 5.0.1 on 2024-04-01 04:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0032_remove_thirdsection_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdsection',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='thirdsection',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='thirdsection',
            name='text2',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thirdsection',
            name='text3',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='thirdsection',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
