# Generated by Django 5.0.1 on 2024-04-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0033_thirdsection_image2_thirdsection_image3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sixthsection',
            old_name='png1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sixthsectiontest',
            old_name='png1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='sixthsectiontest',
            old_name='png2',
            new_name='image2',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='test_png1',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='test_png2',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='test_png3',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='test_subtitle',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='test_title',
        ),
        migrations.RemoveField(
            model_name='sixthsection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sixthsectiontest',
            name='png3',
        ),
        migrations.RemoveField(
            model_name='sixthsectiontest',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='sixthsectiontest',
            name='title',
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sixthsection',
            name='heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sixthsectiontest',
            name='restaurant',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sixthsectiontest',
            name='review',
            field=models.TextField(default='', max_length=200),
        ),
    ]
