# Generated by Django 5.0.1 on 2024-04-01 13:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0034_rename_png1_sixthsection_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fifthsectioncontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourservice_heading', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('ourservice_content', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('ourservice_png', models.ImageField(default='', max_length=200, upload_to='')),
                ('ourservice_link', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_content',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_heading',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_link',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='ourservice_png',
        ),
        migrations.AddField(
            model_name='sixthsectiontest',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
