# Generated by Django 5.0.1 on 2024-04-03 04:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0035_fifthsectioncontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('png1', models.ImageField(upload_to='ourservices/')),
                ('png2', models.ImageField(upload_to='ourservices/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', ckeditor.fields.RichTextField(max_length=255)),
                ('subcontent', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='serviceboxes/')),
            ],
        ),
    ]
