# Generated by Django 5.0.1 on 2024-04-05 09:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0036_ourservice_servicebox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurService',
        ),
        migrations.DeleteModel(
            name='ServiceBox',
        ),
        migrations.RenameField(
            model_name='fifthsectioncontent',
            old_name='ourservice_content',
            new_name='subcontent',
        ),
        migrations.RemoveField(
            model_name='fifthsection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='fifthsectioncontent',
            name='ourservice_heading',
        ),
        migrations.RemoveField(
            model_name='fifthsectioncontent',
            name='ourservice_link',
        ),
        migrations.RemoveField(
            model_name='fifthsectioncontent',
            name='ourservice_png',
        ),
        migrations.AddField(
            model_name='fifthsection',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fifthsectioncontent',
            name='heading',
            field=ckeditor.fields.RichTextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fifthsectioncontent',
            name='image',
            field=models.ImageField(default='', upload_to='serviceboxes/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png1',
            field=models.ImageField(upload_to='ourservices/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png2',
            field=models.ImageField(upload_to='ourservices/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='title',
            field=ckeditor.fields.RichTextField(default='', max_length=255),
        ),
    ]
