# Generated by Django 5.0.1 on 2024-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0037_delete_ourservice_delete_servicebox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifthsection',
            name='png1',
            field=models.ImageField(default='', upload_to='ourservices/'),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png2',
            field=models.ImageField(default='', upload_to='ourservices/'),
        ),
    ]
