# Generated by Django 5.0.1 on 2024-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0038_alter_fifthsection_png1_alter_fifthsection_png2'),
    ]

    operations = [
        migrations.AddField(
            model_name='eighthsection',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
