# Generated by Django 5.0.1 on 2024-04-12 06:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0039_eighthsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsection',
            name='title',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fourthsection',
            name='title',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='title',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
    ]
