# Generated by Django 5.0.1 on 2024-04-15 07:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0041_alter_firstsection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourthsectionbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True)),
                ('posterimage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fourthsection',
            old_name='lap_image',
            new_name='lapimage',
        ),
        migrations.RemoveField(
            model_name='fourthsection',
            name='poster_image',
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
