# Generated by Django 5.0.1 on 2024-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0042_fourthsectionbanner_rename_name_contactform_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
