# Generated by Django 5.0.1 on 2024-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0043_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
    ]
