# Generated by Django 5.0.1 on 2024-04-17 09:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0044_whatsapp_delete_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMfirstsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
