# Generated by Django 5.0.1 on 2024-04-17 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0046_dmsecondsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmsecondsection',
            name='subtitle',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
