# Generated by Django 5.0.1 on 2024-04-18 07:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0047_alter_dmsecondsection_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebookpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dmfirstsection',
            options={'verbose_name_plural': 'DMfirstsection'},
        ),
        migrations.AlterField(
            model_name='sixthsection',
            name='content',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sixthsection',
            name='heading',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='restaurant',
            field=ckeditor.fields.RichTextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='review',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
    ]
