# Generated by Django 5.0.1 on 2024-04-18 10:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0048_facebookpage_alter_dmfirstsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagrampage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dmsecondsection',
            options={'verbose_name_plural': 'DMsecondsection'},
        ),
    ]
