# Generated by Django 5.0.1 on 2024-04-18 11:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0049_instagrampage_alter_dmsecondsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Googlepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Youtubepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
