# Generated by Django 5.0.1 on 2024-04-24 05:27

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0050_googlepage_youtubepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmediapostercontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Socialmediaposterimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
        ),
        migrations.AlterField(
            model_name='dmfirstsection',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='dmsecondsection',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='eighthsection',
            name='logo',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='facebookpage',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png1',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fifthsection',
            name='png2',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fifthsectioncontent',
            name='image',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fourthsection',
            name='lapimage',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fourthsection',
            name='png1',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fourthsection',
            name='png2',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='fourthsectionbanner',
            name='posterimage',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='googlepage',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='secondsection',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='seventhsection',
            name='png',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='sixthsection',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='image1',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='image2',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='sixthsectiontest',
            name='image3',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='thirdsection',
            name='image1',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='thirdsection',
            name='image2',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='thirdsection',
            name='image3',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AlterField(
            model_name='youtubepage',
            name='image',
            field=models.ImageField(upload_to=sample_app.models.get_image_filename),
        ),
    ]
