# Generated by Django 5.0.1 on 2024-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0051_socialmediapostercontent_socialmediaposterimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaposterimages',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
