# Generated by Django 5.0.1 on 2024-04-24 09:18

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0052_socialmediaposterimages_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logoworkcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Logoworkimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Packagedesigncontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Packagedesignimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Uiuxcontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('subtitle', ckeditor.fields.RichTextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Uiuximage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
        ),
    ]
