# Generated by Django 5.0.1 on 2024-04-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0054_videomarketingcontent_videomarketingvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eighthsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Client_logos'},
        ),
        migrations.AlterModelOptions(
            name='facebookpage',
            options={'verbose_name_plural': 'Facebook_Page'},
        ),
        migrations.AlterModelOptions(
            name='fifthsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Ourservice_Data'},
        ),
        migrations.AlterModelOptions(
            name='fifthsectioncontent',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Ourservice_Box_Data'},
        ),
        migrations.AlterModelOptions(
            name='firstsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Home_Section_Data'},
        ),
        migrations.AlterModelOptions(
            name='fourthsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Protfolio_Data'},
        ),
        migrations.AlterModelOptions(
            name='fourthsectionbanner',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Portfolio_Banner'},
        ),
        migrations.AlterModelOptions(
            name='googlepage',
            options={'verbose_name_plural': 'Google_Page'},
        ),
        migrations.AlterModelOptions(
            name='instagrampage',
            options={'verbose_name_plural': 'Instagram_Page'},
        ),
        migrations.AlterModelOptions(
            name='logoworkcontent',
            options={'verbose_name_plural': 'LogoWork_Data'},
        ),
        migrations.AlterModelOptions(
            name='logoworkimage',
            options={'verbose_name_plural': 'LogoWork_Images'},
        ),
        migrations.AlterModelOptions(
            name='packagedesigncontent',
            options={'verbose_name_plural': 'PackageDesign_Data'},
        ),
        migrations.AlterModelOptions(
            name='packagedesignimage',
            options={'verbose_name_plural': 'PackageDesign_Images'},
        ),
        migrations.AlterModelOptions(
            name='secondsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'About_Section_Data'},
        ),
        migrations.AlterModelOptions(
            name='seventhsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Quote_Data'},
        ),
        migrations.AlterModelOptions(
            name='sixthsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Testimonial_Data'},
        ),
        migrations.AlterModelOptions(
            name='sixthsectiontest',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Testimonial_Review'},
        ),
        migrations.AlterModelOptions(
            name='socialmediapostercontent',
            options={'verbose_name_plural': 'SocialMediaPoster_Data'},
        ),
        migrations.AlterModelOptions(
            name='socialmediaposterimages',
            options={'verbose_name_plural': 'SocialMediaPoster_Image'},
        ),
        migrations.AlterModelOptions(
            name='thirdsection',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Services_Data'},
        ),
        migrations.AlterModelOptions(
            name='uiuxcontent',
            options={'verbose_name_plural': 'Uiux_Data'},
        ),
        migrations.AlterModelOptions(
            name='uiuximage',
            options={'verbose_name_plural': 'Uiux_image'},
        ),
        migrations.AlterModelOptions(
            name='videomarketingcontent',
            options={'verbose_name_plural': 'VideoMarketing_Data'},
        ),
        migrations.AlterModelOptions(
            name='videomarketingvideo',
            options={'verbose_name_plural': 'VideoMarketing_video'},
        ),
        migrations.AlterModelOptions(
            name='whatsapp',
            options={'verbose_name': 'Contact Form', 'verbose_name_plural': 'Whatsapp_Data'},
        ),
        migrations.AlterModelOptions(
            name='youtubepage',
            options={'verbose_name_plural': 'Youtube_Page'},
        ),
    ]
