# Generated by Django 5.0.1 on 2024-04-30 06:58

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0055_alter_eighthsection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=2000)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Deliveryservice',
            },
        ),
        migrations.CreateModel(
            name='Ecommerceservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=2000)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Ecommerceservice',
            },
        ),
        migrations.CreateModel(
            name='Servicepageicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Servicepageicon',
            },
        ),
        migrations.CreateModel(
            name='Webdesignservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=2000)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Webdesignservice',
            },
        ),
        migrations.CreateModel(
            name='Webdevelopmentservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=2000)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Webdevelopmentservice',
            },
        ),
    ]
