# Generated by Django 5.0.1 on 2024-04-30 09:51

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0056_deliveryservice_ecommerceservice_servicepageicon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepageicon',
            options={'verbose_name_plural': 'Servicepageicon & text'},
        ),
        migrations.RenameField(
            model_name='servicepageicon',
            old_name='text',
            new_name='delivery_text',
        ),
        migrations.RemoveField(
            model_name='servicepageicon',
            name='image',
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='delivery_image',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='ecommerce_image',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='ecommerce_text',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='webdesign_image',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='webdesign_text',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='webdevelopment_image',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='servicepageicon',
            name='webdevelopment_text',
            field=ckeditor.fields.RichTextField(default='', max_length=200),
        ),
    ]
