# Generated by Django 5.0.1 on 2024-05-10 13:01

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0058_paid_facebookpage_paid_googlepage_paid_instagrampage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seofirstsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', ckeditor.fields.RichTextField(default='', max_length=255)),
                ('subcontent', ckeditor.fields.RichTextField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'SEO_First_Section',
            },
        ),
        migrations.CreateModel(
            name='Seosecondsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=sample_app.models.get_image_filename)),
                ('msgtitle', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('msgcontent', ckeditor.fields.RichTextField(default='', max_length=500)),
                ('msgtitletwo', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('msgcontenttwo', ckeditor.fields.RichTextField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'SEO_Second_Section',
            },
        ),
        migrations.CreateModel(
            name='Seothirdsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('icon', models.ImageField(default='', upload_to=sample_app.models.get_image_filename)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=500)),
                ('image', models.ImageField(default='', upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'SEO_Third_Section',
            },
        ),
    ]
