# Generated by Django 5.0.1 on 2024-05-11 06:06

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0059_seofirstsection_seosecondsection_seothirdsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seothirdsection',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='seothirdsection',
            old_name='icon',
            new_name='icon1',
        ),
        migrations.RenameField(
            model_name='seothirdsection',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='seothirdsection',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='content3',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='icon2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='icon3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='image2',
            field=models.ImageField(default='', upload_to=sample_app.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='title2',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seothirdsection',
            name='title3',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seosecondsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
