# Generated by Django 5.0.1 on 2024-05-14 09:56

import ckeditor.fields
import sample_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0060_rename_content_seothirdsection_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', ckeditor.fields.RichTextField(default='', max_length=200)),
                ('content', ckeditor.fields.RichTextField(default='', max_length=2000)),
                ('image', models.ImageField(upload_to=sample_app.models.get_image_filename)),
            ],
            options={
                'verbose_name_plural': 'Servicepage',
            },
        ),
    ]
